import { DataForGraphType } from "./DataForGraph";

export type GraphType = {
	graphId: string,
	owner: string,
	title?: string,
	type: string,
	metricGroup?: string,
	metricName?: string,
	unitsGroup?: string,
	units?: string,
	xAxisTitle?: string,
	xMetricGroup?: string,
	xMetricName?: string,
	xUnitsGroup?: string,
	xUnits?: string,
	xAutomatic: boolean,
	xMin: string,
	xMax: string,
	xTick: boolean,
	yAxisTitle: string,
	yAutomatic: boolean,
	yMetricGroup?: string,
	yMetricName?: string,
	yUnitsGroup?: string,
	yUnits: string,
	yMin: string,
	yMax: string,
	yTick: boolean,
	grid: boolean,
	dataLabels: boolean,
	lineCurve: boolean,
	labels: string[],
	color: string[],
	thickness?: string[],
	lineType?: string[],
	allData: DataForGraphType[],
	useSuffix: boolean,
	chosenSuffix?: string
}
export const Graph = {
	name: "Graph",
	primaryKey: "graphId",
	properties: {
		graphId: "string",
		owner: "string",
		title: "string?",
		type: "string",
		metricGroup: "string?",
		metricName: "string?",
		unitsGroup: "string?",
		units: "string?",
		xAxisTitle: "string?",
		xMetricGroup: "string?",
		xMetricName: "string?",
		xUnitsGroup: "string?",
		xUnits: "string?",
		xAutomatic: "bool?",
		xMin: "string?",
		xMax: "string?",
		xTick: "bool?",
		yAxisTitle: "string?",
		yAutomatic: "bool?",
		yMetricGroup: "string?",
		yMetricName: "string?",
		yUnitsGroup: "string?",
		yUnits: "string?",
		yMin: "string?",
		yMax: "string?",
		yTick: "bool?",
		grid: "bool?",
		dataLabels: "bool?",
		lineCurve: "bool?",
		labels: "string?[]",
		color: "string[]",
		thickness: "string?[]",
		lineType: "string?[]",
		allData: "DataForGraph[]",
		useSuffix: { type: "bool", default: false },
		chosenSuffix: "string?"
	}
};
